//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WorkShopDBEntities : DbContext
    {
        public WorkShopDBEntities()
            : base("name=WorkShopDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<tbl_Material> tbl_Material { get; set; }
        public DbSet<tbl_Student_WorkShop_Mapping> tbl_Student_WorkShop_Mapping { get; set; }
        public DbSet<tbl_Trainer_Workshop_Mapping> tbl_Trainer_Workshop_Mapping { get; set; }
        public DbSet<tbl_User> tbl_User { get; set; }
        public DbSet<tbl_WorkShop> tbl_WorkShop { get; set; }
    }
}
