//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_User
    {
        public tbl_User()
        {
            this.tbl_Material = new HashSet<tbl_Material>();
            this.tbl_Student_WorkShop_Mapping = new HashSet<tbl_Student_WorkShop_Mapping>();
            this.tbl_Trainer_Workshop_Mapping = new HashSet<tbl_Trainer_Workshop_Mapping>();
            this.tbl_WorkShop = new HashSet<tbl_WorkShop>();
        }
    
        public int UserId { get; set; }
        public string UserName_Email { get; set; }
        public string Password { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string UserGender { get; set; }
        public string Mobile { get; set; }
        public string IsActive { get; set; }
        public Nullable<System.DateTime> UserDob { get; set; }
        public string SkillsSet { get; set; }
        public string Experience { get; set; }
        public Nullable<int> RoleId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual ICollection<tbl_Material> tbl_Material { get; set; }
        public virtual ICollection<tbl_Student_WorkShop_Mapping> tbl_Student_WorkShop_Mapping { get; set; }
        public virtual ICollection<tbl_Trainer_Workshop_Mapping> tbl_Trainer_Workshop_Mapping { get; set; }
        public virtual ICollection<tbl_WorkShop> tbl_WorkShop { get; set; }
    }
}
