//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Trainer_Workshop_Mapping
    {
        public int SerialNo { get; set; }
        public Nullable<int> TrainerId { get; set; }
        public Nullable<int> workShopId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    
        public virtual tbl_User tbl_User { get; set; }
        public virtual tbl_WorkShop tbl_WorkShop { get; set; }
    }
}
