//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_WorkShop
    {
        public tbl_WorkShop()
        {
            this.tbl_Material = new HashSet<tbl_Material>();
            this.tbl_Student_WorkShop_Mapping = new HashSet<tbl_Student_WorkShop_Mapping>();
            this.tbl_Trainer_Workshop_Mapping = new HashSet<tbl_Trainer_Workshop_Mapping>();
        }
    
        public int WorkShopId { get; set; }
        public string WorkShopTitle { get; set; }
        public Nullable<System.DateTime> WorkShopDate { get; set; }
        public string WorkShopDuration { get; set; }
        public string WorkShopTopics { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public string UpdatedDate { get; set; }
    
        public virtual ICollection<tbl_Material> tbl_Material { get; set; }
        public virtual ICollection<tbl_Student_WorkShop_Mapping> tbl_Student_WorkShop_Mapping { get; set; }
        public virtual ICollection<tbl_Trainer_Workshop_Mapping> tbl_Trainer_Workshop_Mapping { get; set; }
        public virtual tbl_User tbl_User { get; set; }
    }
}
