//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Student_WorkShop_Mapping
    {
        public int SerialNo { get; set; }
        public Nullable<int> StudentId { get; set; }
        public Nullable<int> WorkShopId { get; set; }
        public Nullable<bool> IsApproved { get; set; }
    
        public virtual tbl_User tbl_User { get; set; }
        public virtual tbl_WorkShop tbl_WorkShop { get; set; }
    }
}
